spring.application.name=ms-item
server.port=8092

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_item
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.flyway.clean-on-validation-error=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false